### PR TITLE
CURLINFO_TOTAL_TIME

### PR DESCRIPTION
**Pull request by Oxicode**

### CODE REVIEW

**Comment by zachborboa** [comment]
Thanks!

**Comment by thebeline** [comment]
@zachborboa - I hate to do this on a merged PR, but whereas the total time is not something that will always be accessed, and this happens in the `exec` call, it seems not great to add the (minimal, to be sure, but still present) overhead of calling that function for something that may not be used in 90% of use-cases.  For instance, I will nearly never use that information in my usage, but this will always be called...

In a case like #314, this would be moot, and an interesting thing to have.  But otherwise, it seems unnecessary...

**Comment by zachborboa** [comment]
@thebeline You raise a good point. Do you think `Curl::totalTime` would be best removed and do which of the following:

1. Left as is and call as needed; e.g. `$totalTime = curl_getinfo($curl->curl, CURLINFO_TOTAL_TIME);`
1. Implemented as `Curl::getInfo` so `$totalTime = $curl->getInfo(CURLINFO_TOTAL_TIME);`
1. Implemented as `Curl::getTotalTime` so `$totalTime = $curl->getTotalTime();`

**Comment by zachborboa** [comment]
I'm leaning towards implementing `Curl::getInfo` as this will also allow retrieving other information listed on https://secure.php.net/manual/en/function.curl-getinfo.php
```php
$totalTime = $curl->getInfo(CURLINFO_TOTAL_TIME);
$uploadSpeed =  = $curl->getInfo(CURLINFO_SPEED_UPLOAD);
$downloadSpeed =  = $curl->getInfo(CURLINFO_SPEED_DOWNLOAD);
```

**Comment by thebeline** [comment]
Personally?  I like my deferred properties PR, and we could add all of those to the deferred properties list, so:
```
$total_time = $curl->total_time;
$upload_speed = $curl->speed_upload;
// etc.
```
This will cache the results, too, referencing `$curl->total_time;` multiple times just pulls the property on subsequent calls.

That said, sure, I mean, implementing `getInfo()` would be good, it could even be used with deferred properties.  (I'm partial, I know)

**Pull request merged**
