### PR TITLE
fix leak memory

### PR DESCRIPTION
**Pull request by adrianceding**
fix leak memory
**Demo**
```
$multiCurl = new MultiCurl();

for ($i0 = 0; $i0 < 10; $i0++) {
    for ($i = 0; $i <= 1000; $i++) {
        $multiCurl->addGet('http://127.0.0.1/test.php');
    }

    $multiCurl->start();

    echo $i0 . ' Memory: ' . memory_get_usage(true) / 1024 / 1024 . 'MB' . PHP_EOL;
}
echo 'Before Unset MultiCurl Memory: ' . memory_get_usage(true) / 1024 / 1024 . 'MB' . PHP_EOL;
$multiCurl->close();

unset($multiCurl);

echo 'Latest Memory: ' . memory_get_usage(true) / 1024 / 1024 . 'MB' . PHP_EOL;
```

**Result**
0 Memory: 8.25MB
1 Memory: 14.5MB
2 Memory: 21.25MB
3 Memory: 27.75MB
4 Memory: 34MB
5 Memory: 41.25MB
6 Memory: 47.5MB
7 Memory: 53.75MB
8 Memory: 59.75MB
9 Memory: 65.75MB
Before Unset MultiCurl Memory: 65.75MB
Latest Memory: 65.75MB
[Finished in 21.1s]

### CODE REVIEW

**Comment by zachborboa** [comment]
Hi. Memory usage is expected when adding additional requests. I don't see a memory leak here since the memory usage is the same before calling `MultiCurl::close()` and after `close()`/`unset()`.

**Comment by zachborboa** [comment]
```php
$multi_curl = new MultiCurl();

for ($i0 = 0; $i0 < 10; $i0++) {

    for ($i = 0; $i <= 1000; $i++) {
        $multi_curl->addGet(Test::TEST_URL);
    }

    $multi_curl->start();

    echo $i0 . ' memory: ' . memory_get_usage(true) . "\n";
}

echo 'before close: ' . memory_get_usage(true) . "\n";
$multi_curl->close();
echo 'after close:  ' . memory_get_usage(true) . "\n";
unset($multi_curl);
echo 'after unset:  ' . memory_get_usage(true) . "\n";
```
```
0 memory: 16777216
1 memory: 23068672
2 memory: 31457280
3 memory: 37748736
4 memory: 46137344
5 memory: 54525952
6 memory: 60817408
7 memory: 67108864
8 memory: 75497472
9 memory: 83886080
before close: 83886080
after close:  83886080
after unset:  83886080
```

**Comment by adrianceding** [comment]
close and unset multi_curl 
but memory also be used
Is this normal?

**Comment by zachborboa** [comment]
Yes this is expected when using anonymous functions.
https://bugs.php.net/bug.php?id=68132
https://bugs.php.net/bug.php?id=33487
https://bugs.php.net/bug.php?id=69615

Perhaps anonymous functions should be replaced.

**Comment by zachborboa** [comment]
Commented https://github.com/php-curl-class/php-curl-class/issues/439#issuecomment-298226161

**Pull request closed without merging**
