### PR TITLE
JSON associated array Example - Removed json index on response

### PR DESCRIPTION
**Pull request by sganz**
The $curl->response seems to be all that is needed, the 'json' index was invalid when I tried it.

### CODE REVIEW

**Comment by sganz** [comment]
Odd, I'll double check my code, it's all working but I'm not using the the index on the respone and getting things back OK. 

Might be a setting I missed, or something trivial I'm doing that's different. 

Otherwise, working great, made it easy to get the task done.

**Comment by sganz** [comment]
Using Php-Curl-Class - 8.3.2 / Php 7.2.7 on Ubuntu

Here is a snippet of the code. Not sure why (or if I need to) use the 'json' index, but when I do I get an undefined index error. Not sure if their is something else I'm missing.

Here's the snipped of code that I'm using and working OK. 

```        
        $curl = new Curl();
        $curl->setHeader('Content-Type', 'application/json');
        $curl->setDefaultJsonDecoder(true);

        // set up post data
        // $post_dat = [...] ;
        
        $curl->post($vendor_service_url, $post_data);
        $curl->close();

        // $envelope = $curl->response['json']; throws undefined index 'json'
        
        $envelope = $curl->response;
```
$envelope returns the php array with the data.

More for my own learning of what I might be doing wrong...

Sandy

**Comment by zachborboa** [comment]
@sganz the 'json' index is for this particular example so that it displays the POSTed json content:

```
  "json": {
    "content": "Hello world!",
    "date": "2018-10-11 01:23:17",
    "id": "1"
  },
```

Full raw response:
```
{
  "args": {},
  "data": "...",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Content-Length": "64",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "PHP-Curl-Class/8.3.2 (+https://github.com/php-curl-class/php-curl-class) PHP/x.x.x curl/x.x.x"
  },
  "json": {
    "content": "Hello world!",
    "date": "2018-10-11 01:23:17",
    "id": "1"
  },
  "origin": "12.34.56.78",
  "url": "https://httpbin.org/post"
}
```

**Comment by sganz** [comment]
Thanks, totally missed that, didn't even think it was related to content, thought it was a different way to access the resulting JSON data. So obvious now. Thanks for taking the time to explain.

**Pull request merged**
