### PR TITLE
solve site 502 bug

### PR DESCRIPTION
**Pull request by wolaiye1010**
otherwise the site will 502

i don't know why ，but this is true

### CODE REVIEW

**Comment by zachborboa** [comment]
Hi. Can you try this fix https://github.com/php-curl-class/php-curl-class/pull/433/files? Thanks

**Comment by wolaiye1010** [comment]
no ,it doesn't work ,i just try it .
when  program execute “curl_multi_select($this->multiCurl)” 
the site will 502

**Comment by zachborboa** [comment]
@wolaiye1010 can you provide a code snippet to reproduce the problem? Thanks

**Comment by wolaiye1010** [comment]
@zachborboa ,
the code is ：
`<?php
require_once '/server/www/ganji/ganji_online/fuwu/vendor/autoload.php';
ini_set('display_errors','On');

$curl=new \Curl\MultiCurl;
$reflectionClass=new ReflectionClass($curl);
//echo $reflectionClass->getFileName();die;

$curl->setJsonDecoder(function ($response) {
    return json_decode($response, true);
});

$curl->success(function($instance) {
    echo 'call to "' . $instance->url . '" was successful.' . "\n";
    echo 'response:' . "\n";
    var_dump($instance->response);
});

$curl->error(function($instance) {
    echo 'call to "' . $instance->url . '" was unsuccessful.' . "\n";
    echo 'error code: ' . $instance->errorCode . "\n";
    echo 'error message: ' . $instance->errorMessage . "\n";
});

$curl->addGet('http://api.abtest.58corp.com/exp', [
    'cookie' => '6978306004333685185595-853088371',
    'layer' => 'GJHUANGYE_107',
]);

$curl->addGet('http://api.abtest.58corp.com/exp', [
    'cookie' => '6978306004333685185595-853088371',
    'layer' => 'GJHUANGYE_106',
]);

$curl->start();
$curl->close();`

when php-cli execute this code ，it is ok！
bug in nginx php-fpm execute this code , the site will 502，and no error msg, It's magic ！

**Comment by zachborboa** [comment]
I would save and compare the output of `var_dump($curl);` via the command line versus php-fpm. Perhaps there's a difference in the request.

**Comment by wolaiye1010** [comment]
@zachborboa ,thank you for your attention to my question!

**Pull request closed without merging**
