### PR TITLE
Merge #264

### PR DESCRIPTION
**Pull request by zachborboa**

### CODE REVIEW

**Comment by thebeline** [comment]
@zachborboa - Can you add the braces check and `@author` check to your tests so I can handle that prior to PR?

**Comment by zachborboa** [comment]
@thebeline Will do

**Comment by thebeline** [comment]
For what it is worth, `^[ \t]*(?![ \ta-z]*[ \t]+)?function(?![ \t]+[ \ta-z]*)?[ \t]+[a-z_]+\([^\)]+\)[ \t]*{` will detect opening brackets on the same line as the method declaration.

**Comment by thebeline** [comment]
Also, it is rudimentary, but `/^[ \t]+\/\*\*((?!\*\/).)*\n[ \t]+\*[ \t]+@author((?!\*\/).)*\*\//ism` will detect any DocBlock that contains an `@author` tag.

May or may not help.

**Pull request merged**
