### PR TITLE
Add support for Pecl-Compatible headers.

### PR DESCRIPTION
**Pull request by thebeline**
Added support for initialization-flags (although very basic at this time) and support for Pecl-Compatible Headers.

### CODE REVIEW

**Comment by thebeline** [comment]
The question is: Do we want the initialization flags?  Or should that be an setter function?

**Comment by thebeline** [comment]
Never-mind, I amended my commit.  It makes more sense to have it as a setter.

**Comment by thebeline** [comment]
@zachborboa - Is there something blocking this? (I am asking this on a few)

**Comment by zachborboa** [comment]
Hi. Thank you for the pull request. I believe the library correctly parses headers. If you find anything that hasn't been addressed, please let me know.

**Pull request closed without merging**
