### PR TITLE
Deferred properties

### PR DESCRIPTION
**Pull request by thebeline**
Defer parsing certain properties until accessed.

This will only generate properties if accessed when not set, will also clear them on exec call.

Also, some minor performance changes (opcode counting, etc).

### CODE REVIEW

**Comment by thebeline** [comment]
Should resolve #313

**Comment by thebeline** [comment]
Gah, I keep forgetting all sorts of bitty things.  Full disclosure: no, I didn't test, yes, I am using Travis to test.

**Comment by thebeline** [comment]
About time...  You and your tests...  :-D

**Comment by thebeline** [comment]
@zachborboa - Ok, it seems Travis is having a stroke right now.  Again with `nginx` not behaving in `hhvm`, I would consider that last test as passing.

**Comment by thebeline** [comment]
@zachborboa - Were there questions of concerns about this PR?

**Comment by zachborboa** [comment]
Thank you for the pull request. Some of these changes have now been incorporated.

**Pull request closed without merging**
