### PR TITLE
Fix #686: Build url without using data parameter

### LINKED ISSUE #686: MultiCurl POST should not add data automatically as URL params because this leads to 414 Request-URI Too Long
What is the expected behavior?
Optimally, URL params and Body Params can be set individually

What is the actual behavior?
I want to send a body with more than 2000 characters which leads to a `414 Request-URI Too Long`

Issue was introduced in [8.9.4](https://github.com/php-curl-class/php-curl-class/compare/8.9.3...8.9.4#diff-fddc86c3cd09c6f7cf5e5169f91574803ffa90a1a944b2ebd69eb073eea11f06L262)

In this line, the `$data` gets set as URL parameters.
https://github.com/php-curl-class/php-curl-class/blob/712f3555bcf46a84df77aa45c15c2a7fc786a719/src/Curl/MultiCurl.php#L279

### PR DESCRIPTION
**Pull request by tgerakitis**
Also for PATCH, PUT & SEARCH requests

### CODE REVIEW

**Comment by tgerakitis** [comment]
how do I start the server locally on port 8000?

**Comment by zachborboa** [comment]
@tgerakitis you can run the tests like this:
```
$ cd php-curl-class/
$ composer update
$ ./tests/run.sh
```

**Comment by tgerakitis** [comment]
@zachborboa that's exactly what I did.
Even with preexisting tests like checking the user agent  the response is `server.php`.

Is there any way to make sure that the test server is running properly before starting the tests?

**Comment by zachborboa** [comment]
The test server can be manually started using this:
```
cd php-curl-class/tests
export PHP_CURL_CLASS_TEST_MODE_ENABLED="yes"
php -S "127.0.0.1:8000" -t PHPCurlClass/
```

A test request can be made like this:
```
$ curl -i "http://127.0.0.1:8000/?a=1&b=2" -H "X-DEBUG-TEST: get"
HTTP/1.1 200 OK
Host: 127.0.0.1:8000
Date: Wed, 24 Nov 2021 00:00:00 GMT
Connection: close
X-Powered-By: PHP/8
Content-type: text/html; charset=UTF-8

a=1&b=2
```

Also your changes have been merged in https://github.com/php-curl-class/php-curl-class/commit/e999cb4e257d801b576197120a09731472475dc2. Thanks

**Comment by tgerakitis** [comment]
@zachborboa  so I can close this PR right?

**Comment by zachborboa** [comment]
@tgerakitis thank you for your contribution. I'll close this out.

**Pull request closed without merging**
