### PR TITLE
Bug Fix - unsetHeader

### PR DESCRIPTION
**Pull request by KTP95**
There has a bug in unsetHeader()

-----------------

The unsetHeader bad work, 
for example

$curl->setHeader('Host','example.com');
$curl->unsetHeader('Host');
$curl->get('http://127.0.0.1/');

---------
This request is make with Header "Host" = '' (empty string), because unsetHeader bad work

with the my fix the header 'Host' with be deleted and curl auto-retrive the right header.
horever is already possible make request with header 'Host' = '' (empty string) with $curl->setHeader('Host', '' );

also remove a bad comment about fuction
   *		
-     * @return string
in setHeader()

### CODE REVIEW

**Comment by zachborboa** [comment]
Hi. `unsetHeader()` correctly sets the header key without a value causing the header to not be included in the request headers. From the man page:

> Remove an internal header by giving a replacement without content on the right side of the colon, as in: -H "Host:". If you send the custom header with no-value then its header must be terminated with a semicolon, such as -H "X-Custom-Header;" to send "X-Custom-Header:".

http://curl.haxx.se/docs/manpage.html#-H

**Comment by zachborboa** [comment]
Example test:

```php
// index.php
echo $_SERVER['HTTP_X_FOO'];
```

```php
$curl = new Curl();
$curl->setHeader('X-FOO', 'BAR');
$curl->post('http://127.0.0.1:8000');
echo $curl->rawResponse . "\n"; // returns 'BAR'
```

```php
$curl = new Curl();
$curl->setHeader('X-FOO', 'BAR');
$curl->unsetHeader('X-FOO');
$curl->post('http://127.0.0.1:8000');
echo $curl->rawResponse . "\n"; // returns 'Notice: Undefined index: HTTP_X_FOO'
```

**Comment by KTP95** [comment]
OK, you are right, I Dont know curl 100%, i'm sorry. but there are a problem:

By Default Curl send the following headers with a value auto-retrieve:

Request-Line
Host
Accept
--------
So if i force another value, for example for "Host" with

$curl->setHeader('Host', 'example.com');

Don't exist a method, in your class for restore to 'Host' a default value that is auto-retrived

I thought that unsetHeader will be planned for do this, but it is planned for Remove header, not for restore, so is missing a method: setDefaultHeader

**Comment by KTP95** [comment]
Horever in your class there're a bug, please try this

$curl = new Curl();
$curl->unsetHeader('Host');
$curl->setHeader('X-FOO', 'BAR');
$curl->get('http://srv1.cb01.pw:5553/test/');

the header 'Host' will be reset to default value and it is present in the request

unsetHeader() function must be edit and remove the unset 

    /**
     * Unset Header
     *
     * @access public
     * @param  $key
     */
    public function unsetHeader($key)
    {
        $this->setHeader($key, '');
    }

**Comment by KTP95** [comment]
please let see if everything is ok

/**
     * Set Default Header
	 * @param  $key
     *
     * @access public
     */
    public function setDefaultHeader($key)
    {
        unset($this->headers[$key]);
        $this->buildHeaders();
    }

So, usage

$curl = new Curl();
$curl->setHeader('Host', 'example.com');
$curl->get('http://127.0.0.1:8000/');

is

 [requestHeaders] => CaseInsensitiveArray Object
        (
            [container:CaseInsensitiveArray:private] => Array
                (
                    [Request-Line] => GET /test/ HTTP/1.1
                    [User-Agent] => PHP-Curl-Class/4.6.9 (+https://github.com/php-curl-class/php-curl-class) PHP/5.4.16 curl/7.29.0
                    [Accept] => */*
                    [Host] => example.com
                )

        )


with 

$curl = new Curl();
$curl->setHeader('Host', '');
$curl->get('http://127.0.0.1:8000/');

is


   [requestHeaders] => CaseInsensitiveArray Object
        (
            [container:CaseInsensitiveArray:private] => Array
                (
                    [Request-Line] => GET /test/ HTTP/1.1
                    [User-Agent] => PHP-Curl-Class/4.6.9 (+https://github.com/php-curl-class/php-curl-class) PHP/5.4.16 curl/7.29.0
                    [Accept] => */*
                )

        )


with

$curl = new Curl();
$curl->setHeader('Host', 'example.com');
$curl->setDefaultHeader('Host');
$curl->get('http://example.com/');

is

 [requestHeaders] => CaseInsensitiveArray Object
        (
            [container:CaseInsensitiveArray:private] => Array
                (
                    [Request-Line] => GET /test/ HTTP/1.1
                    [User-Agent] => PHP-Curl-Class/4.6.9 (+https://github.com/php-curl-class/php-curl-class) PHP/5.4.16 curl/7.29.0
                    [Host] => example.com
                    [Accept] => */*
                )

        )

I Thinks is all right now, 

Confirm ?

**Comment by zachborboa** [comment]
Can you provide a use case for implementing `Curl::setDefaultHeader`?

**Comment by zachborboa** [comment]
As mentioned in https://github.com/php-curl-class/php-curl-class/pull/237#issuecomment-134778822, `unsetHeader()` unsets the header you previously set. It does not reset any header. A use case is needed for implementing `Curl::setDefaultHeader`.

**Comment by zachborboa** [comment]
Additional note, think of `unsetHeader()` as `removeHeader()` which will remove an internal header.

**Comment by zachborboa** [comment]
Reopening to implement separate `unsetHeader()` and `removeHeader()`.

**Comment by zachborboa** [comment]
Thanks for the suggestion!

**Pull request closed without merging**
