### PR TITLE
implementing get cookie functionality

### PR DESCRIPTION
**Pull request by fealXX**
Added the ability to get elements from the Cookiearray (also after a request).

### CODE REVIEW

**Comment by zachborboa** [comment]
Hi. Thank you for the pull request.

Using `getCookie` could return an unexpected value. Consider this scenario:

```php
$curl = new Curl();

$curl->setCookie('foo', 'bar');
echo $curl->getCookie('foo'); // returns "bar" as expected

$curl->get('https://www.example.com/'); // response changes cookie foo to "baz"
echo $curl->getCookie('foo'); // returns "baz", not "bar"
```

Do you think this is acceptible behavior going forward?

**Comment by fealXX** [comment]
I mostly focused on getting the values after a request, my use case was looking more like that:

    $curl = new Curl();
    $curl->setCookieFile(realpath(dirname(__FILE__)).'/cookie.txt');
    $curl->setCookieJar(realpath(dirname(__FILE__)).'/cookie.txt');
    
    $curl->get('https://www.example.com/'); //sets Session or something
    echo $curl->getCookie('foo'); 

So I wasn't trying to replace the CookieJar functionality and did not look into setCookie.
Your example is still the behavior I would expect, since the server is telling me that the new "correct" Value for foo should be baz, but maybe it would be better to go for a solution replacing setCookieFile/setCookieJar or editing it to be getResponseCookieValue().

**Comment by zachborboa** [comment]
Perhaps renaming `getCookie` to `getRequestCookie` and adding `getResponseCookie` would clear things up.

**Comment by fealXX** [comment]
Gonna re-submit it with the changes. :)

**Pull request closed without merging**
