### PR TITLE
Volume fixes

### PR DESCRIPTION
**Pull request by thebeline**
A couple of fixes for downloads of "volume"

1. I noticed that `$mc = new MultiCurl; unset($mc);` does not call `__destruct` (in fact, `$c = new Curl; unser($c);` doesn't either) as the $ch is still referenced by `curl()`, etc, so, for convenience, I added `autoClose` that will automatically call `$ch->close()`, which will destruct the objects and free up memory consumed by them.
2. When calling many downloads, I wanted to be able to manage the concurrency of the downloads, so I added `concurrency()`.  Now, only X downloads will process at once.  This manages an internal queue, and it will process all by default (concurrency of `0`).
3. Also when managing many downloads (think, thousands) I hit a file pointer ceiling.  I mitigated this by deferring the creating of the file pointers until `initHandle()` is called, which will stay within the concurrency limits.

Hope this finds you well.

### CODE REVIEW

**Comment by zachborboa** [comment]
3ad8997bb9f9784f3c8d9f1a686abd0c9bfc1471 - Can this commit be broken out as a separate pr? Possibly related to #307.

**Comment by thebeline** [comment]
@zachborboa - I believe you are referring to `b226bad`?

**Comment by thebeline** [comment]
@zachborboa - All of these commits, actually, all of these commits, will resolve and mitigate #307.  So...  :-/  no?

Simply differing the creation does no stop too many handles, as they will all be queued on start.  Also, without closing, even concurrency will not stop it, as the handles will remain open while the object is un-closed due to the handle still being referenced by the open curl handle, which will remain referenced due to a circular reference between the Curl object, and the curl handle.

These must remain together to resolve that issue.

**Comment by thebeline** [comment]
@zachborboa - What am I failing on in CI?

**Comment by zachborboa** [comment]
@thebeline It's getting caught up by https://github.com/php-curl-class/php-curl-class/blob/master/tests/script.sh

Tab characters.

> Tab character found in ./src/Curl/MultiCurl.php:43:	 * Auto Close 
Tab character found in ./src/Curl/MultiCurl.php:44:	 *
Tab character found in ./src/Curl/MultiCurl.php:45:	 * Wether to auto-close child Curl Requests one complete
Tab character found in ./src/Curl/MultiCurl.php:46:	 * 
Tab character found in ./src/Curl/MultiCurl.php:47:	 * @param bool $true (optional)
Tab character found in ./src/Curl/MultiCurl.php:48:	 * 
Tab character found in ./src/Curl/MultiCurl.php:49:	 * @return void
Tab character found in ./src/Curl/MultiCurl.php:50:	 * 
Tab character found in ./src/Curl/MultiCurl.php:51:	 * @access public 
Tab character found in ./src/Curl/MultiCurl.php:52:	 */

**Comment by thebeline** [comment]
@zachborboa - GAH!  You have some of the most annoying CI rules evar...  lol  Every time I try to open a PR with you, I spend as much time fixing spaces/tabs/caps/etc as I did writing the code in the first place...  :-P

**Comment by thebeline** [comment]
@zachborboa - betterer.  That PHP 7 memory leak is a doozey...

**Comment by zachborboa** [comment]
Thanks for the pull request. The issues addressed should now be resolved.

**Pull request closed without merging**
